# Generated by hand for initial schema
from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def seed_categories_forward(apps, schema_editor):
    Category = apps.get_model("catalog", "Category")
    defaults = ["Skincare", "Makeup", "Haircare", "Fragrance"]
    for name in defaults:
        Category.objects.get_or_create(name=name, slug=slugify(name))


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(help_text='URL-safe slug for the category.', max_length=140, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(db_index=True, max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=0, help_text='Average rating from 0.0 to 5.0', max_digits=3)),
                ('image_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(help_text='Stock keeping unit.', max_length=64, unique=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='catalog.tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='catalog_pro_brand_2a79a8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='catalog_pro_name_bab6b4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['in_stock'], name='catalog_pro_in_sto_0aab61_idx'),
        ),
        migrations.RunPython(seed_categories_forward, migrations.RunPython.noop),
    ]
