# Generated by Django 5.2 on 2026-01-09 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_brand_f6911e_idx',
            old_name='catalog_pro_brand_2a79a8_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_name_f603c0_idx',
            old_name='catalog_pro_name_bab6b4_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_in_stoc_df7d56_idx',
            old_name='catalog_pro_in_sto_0aab61_idx',
        ),
    ]
